POST http://localhost:4000/student/apply
Content-Type: application/json
Cookie: gatepass_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwM2FiZGIyZC03NWI5LTQ3NzMtYTUyOC1mZmM5MThlMTMyYTciLCJlbWFpbCI6IjIyMDcxYTA1MDhAdm5ydmppZXQuaW4iLCJuYW1lIjoiTmFnYSBTYWkgS2lyYW4iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0OTY2MDE5MywiZXhwIjoxNzUwMjY0OTkzfQ._wpKXbo_iSz1MP6hA1On7X-FYBUcpXcCKYAGC2YhNgs

{
  "reason": "vinayakudi pooja"
}


### Student applies for gate pass
POST http://localhost:4000/student/apply
Content-Type: application/json
Cookie: gatepass_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5MTQyYmMyLTFiOTYtNDEzMy1iNzRkLWIwZmFkNGE2NzFlYyIsImVtYWlsIjoiMjIwNzFhMDUwOEB2bnJ2amlldC5pbiIsIm5hbWUiOiJOYWdhIFNhaSBLaXJhbiIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNzUwNzY5MTc5LCJleHAiOjE3NTA4NTU1Nzl9._O-bs1riiGuqFErNCyUvdXMordD4lbnQ5bjdFM3ubkc

{
  "reason": "valorant contest"
}

### Mentor views pending requests
GET http://localhost:4000/mentor/requests
Cookie: gatepass_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5Mzg3ODIzZC05NzgzLTRmNDktYTYyMC05YzY2ZWY1MjMzNWUiLCJlbWFpbCI6ImF2ZWVub25pZ2h0c0BnbWFpbC5jb20iLCJuYW1lIjoiSm9lIEFsd3luIiwicm9sZSI6Ik1FTlRPUiIsImlhdCI6MTc0OTY2MDM1MywiZXhwIjoxNzUwMjY1MTUzfQ.SBYX-RLOYw3JyhiH1opM9h5tR_GTtDTjpTkfbmsz2mc


### Logout
POST http://localhost:4000/logout
Cookie: gatepass_token=PeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwM2FiZGIyZC03NWI5LTQ3NzMtYTUyOC1mZmM5MThlMTMyYTciLCJlbWFpbCI6IjIyMDcxYTA1MDhAdm5ydmppZXQuaW4iLCJuYW1lIjoiTmFnYSBTYWkgS2lyYW4iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc0OTY1NDkwOCwiZXhwIjoxNzUwMjU5NzA4fQ.3kr25GsQhk_gW6M5uewPzAXIB_Wdqz9U8ET1nlbIWjM

### Mentor views pending gate pass requests
GET http://localhost:4000/mentor/requests
Cookie: gatepass_token=PASTE_MENTOR_TOKEN_HERE

### mentor responding to requets
GET http://localhost:4000/mentor/requests
Cookie: gatepass_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5Mzg3ODIzZC05NzgzLTRmNDktYTYyMC05YzY2ZWY1MjMzNWUiLCJlbWFpbCI6ImF2ZWVub25pZ2h0c0BnbWFpbC5jb20iLCJuYW1lIjoiSm9lIEFsd3luIiwicm9sZSI6Ik1FTlRPUiIsImlhdCI6MTc0OTY2MDM1MywiZXhwIjoxNzUwMjY1MTUzfQ.SBYX-RLOYw3JyhiH1opM9h5tR_GTtDTjpTkfbmsz2mc

###posting from mentor side (reject/approve)
POST http://localhost:4000/mentor/respond
Content-Type: application/json
Cookie: gatepass_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5Mzg3ODIzZC05NzgzLTRmNDktYTYyMC05YzY2ZWY1MjMzNWUiLCJlbWFpbCI6ImF2ZWVub25pZ2h0c0BnbWFpbC5jb20iLCJuYW1lIjoiSm9lIEFsd3luIiwicm9sZSI6Ik1FTlRPUiIsImlhdCI6MTc0OTY1NjExNSwiZXhwIjoxNzUwMjYwOTE1fQ.oSwvGUBszDk0nlvyu8OOWaoWFIDG04Lsw1SL0dTImjo

{
  "gatePassId": "c0656a5d-cbb0-4dc2-97e8-7efef7321179",
  "action": "APPROVE",
  "comment": "enjoy pandago."
}


### Get Assigned Mentor for Logged-in Student
GET http://localhost:4000/student/mentor
Cookie: gatepass_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAzYWJkYjJkLTc1YjktNDc3My1hNTI4LWZmYzkxOGUxMzJhNyIsImVtYWlsIjoiMjIwNzFhMDUwOEB2bnJ2amlldC5pbiIsIm5hbWUiOiJOYWdhIFNhaSBLaXJhbiIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNzUwNzQ0NzczLCJleHAiOjE3NTA4MzExNzN9.n52bj5He1C9k5g4eEoghSXnRC-K8_CsOaTIsEjVr7XI


### Test working QR scan route
GET http://localhost:4000/api/security/scan/1	3be7d23e-4271-4f74-a06d-93da98f7a8a2/ABPTUWA2W4
Cookie: gatepass_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY2NGI2ZjhjLTZmZGMtNGM5Zi05ZGUyLTEyMzQ1Njc4OWFiYyIsImVtYWlsIjoia2lsbHVheGtpbGx1YTAwQGdtYWlsLmNvbSIsIm5hbWUiOiJTZWN1cml0eV9HdWFyZCIsInJvbGUiOiJTRUNVUklUWSIsImlhdCI6MTc1MDc5MzUxMiwiZXhwIjoxNzUwODc5OTEyfQ.157o7Ft-0rwm8Y2snJinwpSkyWgT67X5GAdM1f6-OZ0
# (You can copy full cookie from Chrome devtools -> Application -> Cookies)

